apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-k8s-mysql
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: springboot-crud-k8s
          image: kubernatetraining.azurecr.io/ankit8983/springbootapp:latest
          ports:
            - containerPort: 12001   # ✅ match Spring Boot app port
          env:   # Setting Environmental Variables
            - name: DB_HOST
              value: "ankitmysqlazure.mysql.database.azure.com"
            - name: DB_NAME
              value: "ankitmysql"
            - name: DB_USERNAME
              value: "AnkitSQL"
            - name: DB_PASSWORD
              value: "Anjali@123"
            - name: DB_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-crud-svc
spec:
  selector:
    app: springboot-k8s-mysql
  ports:
    - protocol: TCP
      port: 8080        # ✅ cluster/external port
      targetPort: 12001 # ✅ forwards to container port
  type: LoadBalancer
